mytestkey=This value is from DOCKER properties file

processing.create.payment.url=http://processing:8082/payments
processing.initiate.payment.url=http://processing:8082/payments/{txnReference}/initiate
processing.capture.payment.url=http://processing:8082/payments/{txnReference}/capture
cancel.url=https://example.com/cancelUrl
return.url=https://example.com/returnUrl
